server_name = 'Gauss'

app_name = 'app3'
app_root = '/Users/ondrej/Documents/GitHub/bkp/bkp/testdata/app1/'

included_paths = ['**/*']
excluded_paths = ['logs.txt']

pre_backup_script = '/Users/ondrej/Documents/GitHub/bkp/bkp/testdata/scripts/app1/pre_backup.sh'
post_backup_script = '/Users/ondrej/Documents/GitHub/bkp/bkp/testdata/scripts/app1/post_backup.sh'

pre_restore_script = ''
post_restore_script = ''

keep_full_local_backups = 1
keep_full_remote_backups = 5
